feat(security_groups): add support for Security Group Rules
krystal/go-katapult pull request #111
Opened 2021-06-01 12:42 UTC by andrewjtait

2021-06-01 12:56 UTC, strideynet approved these changes

2021-06-01 14:54 UTC, jimeh requested changes
I only have a few small things and some nitpicks, overall looks very good :)

2021-06-01 14:54 UTC, jimeh commented on core/security_group_rule.go
> +	return v
Minor nitpick to simplify this like the `(SecurityGroupRef) queryValues()` method.

```suggestion
	return &url.Values{"security_group_rule[id]": []string{sgr.ID}}
```

2021-06-01 14:54 UTC, jimeh commented on core/security_group_rule.go
> +	Notes     string   `json:"notes,omitempty"`
Is it possible to specifically set `Targets` or `notes` to a empty list (remove existing targets), and empty string (clear out existing notes value)? If so these will need to be pointer types so we can differentiate between unchanged and clear updates.

2021-06-01 14:54 UTC, jimeh commented on core/security_group_rule.go
> +type SecurityGroupRuleCreateRequest struct {
This struct doesn't need to be exported, as it's only used for internal request purposes.

2021-06-01 14:54 UTC, jimeh commented on core/security_group_rule.go
> +type SecurityGroupRuleUpdateRequest struct {
This struct doesn't need to be exported, as it's only used for internal request purposes.

2021-06-01 14:54 UTC, jimeh commented on core/security_group_rule.go
> +type SecurityGroupRulesResponseBody struct {
This struct doesn't need to be exported, as it's only used for internal request purposes.

2021-06-01 14:54 UTC, jimeh commented on core/security_group_rule_test.go
> +func TestSecurityGroupRulesClient_List(t *testing.T) {
Very minor nitpick, but I like ordering the tests for different functions in the same order as the function themselves in the implementation file :)

2021-06-01 14:54 UTC, jimeh commented on core/security_group_rule.go
> +}
There's no JSON marshaling tests for this struct, though I've noticed that's actually an oversight missing from nearly every single `*Ref` type we have, and needs to be addressed. But let's add it for security group rules here to begin with :)

2021-06-01 14:54 UTC, jimeh commented on core/client.go
> +		SecurityGroups:                  NewSecurityGroupsClient(rm),
Setting up a new `SecurityGroupsClient` here probably belongs in #103 :)

2021-06-01 16:43 UTC, jimeh requested changes

2021-06-01 16:43 UTC, jimeh commented on core/security_group_rule.go
> +	Notes     *string   `json:"notes,omitempty"`
For this struct these fields actually don't need to be pointer types, as it's used to hold rule information received from the API. It's only the `SecurityGroupRuleArguments` struct where they need to be pointers so we can differentiate in JSON between not sending the key at all or explicitly setting it to empty string/array when creating/updating rules.

2021-06-03 08:21 UTC, andrewjtait commented
@jimeh also ready for re-review 🙏

2021-06-03 10:33 UTC, jimeh approved these changes

2021-06-04 12:16 UTC, merged